[features]
seeds = false
skip-lint = false
[programs.localnet]
ido_pool = "BRFToHyskhgosAcNDCGRF7v5ENwheanfSSvdUVAqpSi1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/cloud/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
